version: '3.7'
services:
  bot:
    build: tg_bot
    command: "python -m bot"
    env_file:
      - tg_bot/bot/.env
    restart: always

  robot:
    build: Version20.03.2023
    image: robot
    devices:
      - /dev/video0
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./Version20.03.2023/:/home/sergh/
    tty: true